INSERT INTO customer (full_name) VALUES('Stywar Vargas Chino')
INSERT INTO customer (full_name) VALUES('Leonel Messi')
INSERT INTO customer (full_name) VALUES('Paolo Guerrero')
INSERT INTO customer (full_name) VALUES('Andrea Pirlo')
INSERT INTO customer (full_name) VALUES('Renato Tapia')

INSERT INTO account(total_amount,id_customer) VALUES(1000,1)
INSERT INTO account(total_amount,id_customer) VALUES(5000,1)
INSERT INTO account(total_amount,id_customer) VALUES(300,2)
INSERT INTO account(total_amount,id_customer) VALUES(600,1)
INSERT INTO account(total_amount,id_customer) VALUES(400,2)
INSERT INTO account(total_amount,id_customer) VALUES(100,1)
INSERT INTO account(total_amount,id_customer) VALUES(1000,3)
INSERT INTO account(total_amount,id_customer) VALUES(2000,4)
INSERT INTO account(total_amount,id_customer) VALUES(5000,5)
INSERT INTO account(total_amount,id_customer) VALUES(1000,2)