version: '2.1'

services:  
  tracer:
    image: openzipkin/zipkin:2
    container_name: service-tracer
    restart: always
    ports:
      - "9411:9411"
    networks:
    - aforo255 
  metrics:
    image: prom/prometheus:v2.31.1
    container_name: service-metrics
    restart: always
    ports:
    - 9090:9090
    networks:
    - aforo255
    volumes:
    - c:/docker/java/prometheus.yml:/etc/prometheus/prometheus.yml
  analytics:
    image: grafana/grafana:8.2.3
    container_name: service-analytics
    restart: always
    ports:
    - 3000:3000
    networks:
    - aforo255
    depends_on:
    - metrics

networks:
  aforo255:
    name: micro-java-1